CREATE TABLE todos
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description text NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY(id)
) ENGINE=INNODB
