CREATE TABLE addresses
(
  id BIGINT NOT NULL auto_increment,
  user_id varchar(100) NOT NULL,
  address varchar(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=INNODB
