CREATE TABLE wallets
(
  id VARCHAR(100) NOT NULL,
  user_id VARCHAR(100) NOT NULL,
  balance BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=INNODB
